### PR TITLE
First attempt: Warn about samples skipped due to low alignment.

### PR DESCRIPTION
**Pull request by ewels**
Needs testing..

### CODE REVIEW

**Comment by ewels** [comment]
Should be fairly easy to test - just run the pipeline with the wrong genome..

**Comment by ewels** [comment]
TODO: Would be nice to add this information to the MultiQC report as well.

**Comment by ewels** [comment]
Ok, tested and working! Still doesn't end up in the MultiQC report yet, but gets into the pipeline report and email.

Phil

**Comment by Hammarn** [comment]
Looks good to me!

**Pull request merged**
