### PR TITLE
Bunch of minor tweaks / version refactor / MultiQC fix

### PR DESCRIPTION
**Pull request by ewels**
NB: This is currently broken I think. Seems to hang after the software versions process.

### CODE REVIEW

**Comment by Hammarn** [comment]
This is a really nice change. As soon as we can get it actually working then I'm happy to merge.

**Comment by ewels** [comment]
Pulled upstream changes and rebased, to make it easier to run same tests locally.

**Comment by ewels** [comment]
Still hanging before running MultiQC. Worked it down to a minimal example and have an issue open here: https://github.com/nextflow-io/nextflow/issues/611

**Comment by ewels** [comment]
Ping @Hammarn - ready for merge if you’re happy.

**Comment by ewels** [comment]
yass

**Pull request merged**
