### PR TITLE
Config + docs for running on AWS using built-in Nextflow tools

### PR DESCRIPTION
**Pull request by ewels**

### CODE REVIEW

**Comment by ewels** [comment]
I would quite like someone to run through these instructions to test them / see what I'm missing before this is merged.. Perhaps @Hammarn or @Galithil tomorrow?

**Comment by ewels** [comment]
Accidentally appended onto this PR - new functionality to generate a summary HTML report describing the completed pipeline. This is sent if the new `params.email` is set to an e-mail address. Has more extensive use of `workflow.runName`, which can be set on the command line with `-name`.

Also - testing profiles (`testing`, `uppmax-devel` and `amazon_test`) now automatically save the trace and timeline report to the results directory.

Phil

**Comment by ewels** [comment]
Example of a pipeline that ran successfully:
screencapture-file-users-philewels-github-ngi-rnaseq-tests-results-documentation-pipeline_report-html-1494000498603

Example of a pipeline that failed:
screencapture-file-users-philewels-github-ngi-rnaseq-tests-results-documentation-pipeline_report-html-1494000752327

**Comment by ewels** [comment]
NB: Travis tests are failing because the trace and timelines currently require the target directory to exist. This is fixed in Nextflow but not yet released: https://github.com/nextflow-io/nextflow/issues/334

**Comment by Hammarn** [comment]
Tested, and approved!

**Pull request merged**
