### PR TITLE
Config update (max limits, new devel)

### PR DESCRIPTION
**Pull request by ewels**
- Add maximum constraints for job requests.
  - New `params.max_memory`, `max_cpus` and `max_time` options
  - Process configs now apply `Math.min()` using these so that submissions never go above limits.
- Changed `devel` config to inherit and overwrite main uppmax config.
  - Instead of having two duplicate configs, attempt to load both in the main `nextflow.config` file and overwrite the things that should be different.

#### Currently all completely untested, so may not work.

### CODE REVIEW

**Comment by Hammarn** [comment]
Looks really good, nice simlple implementation.
I'll give it a test and if it works out i'll merge it.

**Comment by Hammarn** [comment]
Whoops:
```
ERROR ~ Error executing process > 'trim_galore (SRR4238359_subsamp)'

Caused by:
  No signature of method: static java.lang.Math.min() is applicable for argument types: (nextflow.util.MemoryUnit, nextflow.util.MemoryUnit) values: [16 GB, 128 GB]
Possible solutions: min(double, double), min(float, float), min(int, int), min(long, long), find(), sin(double)
```

**Comment by ewels** [comment]
Hey @Hammarn,

I've tried actually testing this code locally and on uppmax with uppmax-devel. Seems to work ok now. Note that I clear up a couple of other minor bugs / warnings in this now as well.

Phil

**Comment by ewels** [comment]
Ok, I just added a bigger refactoring of the config whilst I was there, to avoid duplication. That last commit is slightly less well tested currently.

**Comment by Hammarn** [comment]
Good job on this @ewels I tested it and I'm happy to merge now!

**Pull request merged**
