### PR TITLE
Added a merge script for FeatureCounts output

### PR DESCRIPTION
**Pull request by Hammarn**
Attempt at resolving  #82 
I'm able to generate the output file but I end up with multiples copies of each line. There's something wrong in my logic. 

example:
```
ENSAMBLE_ID	P7352_1001_S41_L003_R1_001	P7352_1002_S42_L003_R1_001	P7352_1002_S42_L003_R2_001	P7352_1003_S43_L003_R1_001	P7352_1003_S43_L003_R2_001	P7352_1004_S44_L003_R1_001	P7352_1004_S44_L003_R2_001	P7352_1005_S45_L003_R1_001	P7352_1005_S45_L003_R2_001	P7352_1006_S46_L003_R1_001	P7352_1006_S46_L003_R2_001	P7352_1007_S47_L003_R1_001	P7352_1007_S47_L003_R2_001	P7352_1008_S48_L003_R1_001	P7352_1008_S48_L003_R2_001
ENSG00000000003	0	0	29	0	0	0	3	0	123	0	93	0	0	0	19
ENSG00000000003	0	0	29	0	0	0	3	0	123	0	93	0	0	0	19
ENSG00000000003	0	0	29	0	0	0	3	0	123	0	93	0	0	0	19
ENSG00000000003	0	0	29	0	0	0	3	0	123	0	93	0	0	0	19
ENSG00000000003	0	0	29	0	0	0	3	0	123	0	93	0	0	0	19
ENSG00000000003	0	0	29	0	0	0	3	0	123	0	93	0	0	0	19
ENSG00000000003	0	0	29	0	0	0	3	0	123	0	93	0	0	0	19
ENSG00000000003	0	0	29	0	0	0	3	0	123	0	93	0	0	0	19
ENSG00000000003	0	0	29	0	0	0	3	0	123	0	93	0	0	0	19```

### CODE REVIEW

**Comment by ewels** [comment]
I'm confused - this PR shows a single commit that is changing a file. However, that file isn't in the main repo. Is there some strange rebasing going on here or something?

**Comment by Hammarn** [comment]
Yes there is, I pushed the version change for StringTie to master not realizing that I had also commits regarding to this. I thought removing the file and then making this PR would resolve that. Apparently not, and I realise that that is due to my earlier commits already being present on the main repo.

**Comment by ewels** [comment]
You pushed direct to master? 😱

**Comment by Hammarn** [comment]
Cleaned upp my mess, mostly. Closed this and opened #95

**Pull request closed without merging**
