### PR TITLE
Finished #140: Add --help and version checks

### PR DESCRIPTION
**Pull request by ewels**
Finished up the software version check stuff.

### CODE REVIEW

**Comment by ewels** [comment]
Closes #138

**Comment by ewels** [comment]
I wrote a few new MultiQC modules and am writing some more now. I think I'll probably push a MultiQC release soon as a result, so we can wait for that. I'm thinking next week at the latest.

Phil

**Comment by Hammarn** [comment]
That sounds like a plan. We merge this and make new release of this pipeline when the new MultiQC release is out.

**Comment by ewels** [comment]
Yup, sounds good 👍

**Comment by ewels** [comment]
Ping @Hammarn ;)

**Comment by Hammarn** [comment]
@ewels https://github.com/ewels/MultiQC/releases

**Comment by ewels** [comment]
@Hammarn - this can be merged now! 🎉

**Pull request merged**
