### PR TITLE
Large refactor / HISAT2 compatibility / working index building

### PR DESCRIPTION
**Pull request by ewels**
* Option to align using HISAT2 with the `--align hisat2` command line parameter.
* Lots of stuff moved from the pipeline file into the config file
* Moved scripts out into their own files in `bin`
* Switched BED conversion from BEDOpts to `gtf2bed` script, which actually works with RSeQC
* Some of @Galithil's Docker stuff in with this PR
  * Better R package installations
  * Fixed broken Fasta / GTF download links for GRCh37

### CODE REVIEW

**Comment by Hammarn** [comment]
So what't the test situation with this @ewels?

**Comment by ewels** [comment]
I've run single-end and paired-end tests with HISAT2 on subsampled data, and it's worked fine (with the exception of preseq falling over as it was subsampled). I ran tests with star a little while ago and that was fine also, though I haven't repeated that recently.

Basically, I think it should be fine. But it'd be good to test it on a proper project please :) HISAT2 and STAR now. Can also run `-with-timeline` to get profiles at the same time.

**Comment by Hammarn** [comment]
Running a test on some actual data, will come back with feedback after that.

**Comment by Hammarn** [comment]
Test finished fine, merging!

**Pull request merged**
